// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace UICatalog
{
	public partial class SearchPresentOverNavigationBarViewController : UITableViewController
	{
		public SearchPresentOverNavigationBarViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
